### ISSUE TITLE
Design Standard

### ISSUE THREAD

**Issue by Durban-Designer** [Screen-Art-Studios/Total-Response#1]
The completed design standard should be a pdf with a resolution of 300ppi. 
it should also meet all of the following guidlines;
-quality logos and alternates
-all colors used in the project
-styling for buttons
-styling for divs and related boxes
-fonts
-font-sizing, line-height, and line length
-tone of the application
-quality mission statement
-styling for all input boxes
-animation design statement ie"draw the users eye towards the next step, only initiate on user action, etc.."
-animation descriptions
-must look good when printed in booklet format
-reference screen art brand in a meaningful fashion
-be organized in a logical ordering and solid flow.

**Comment by Spiralis-Solutions** [comment]
@McKibbN Gonna need you to make me some icons and buttons. Such as: phone, phone call end, speakerphone, settings, Just some Icos for generic things needed within the app, then give em to me to put in with the rest of the DS

**Comment by 42shotfirst** [comment]
Keep in mind that we can use iOS kit icons for most of this, if you need anything i can send these to you. Android can be grabbed from Google's repository

**Comment by Spiralis-Solutions** [comment]
Yes that would be great, For now at least and if you want custom ones that would obviously be no issue.
